# Generated by Django 5.2.1 on 2025-05-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosMedicos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.TextField()),
                ('nombre', models.TextField()),
                ('especialidad', models.TextField()),
                ('qir', models.TextField()),
                ('tiene_consulta', models.TextField()),
                ('tiene_proced', models.TextField()),
                ('proced_a_realizar', models.TextField()),
                ('piso_atencion', models.TextField()),
                ('nuevo_piso_desde_septiembre', models.TextField()),
                ('vigencia', models.TextField()),
                ('frecuencia', models.TextField()),
                ('dias_atencion', models.TextField()),
                ('cantidad_horas', models.TextField()),
                ('cantidad_minutos', models.TextField()),
                ('pctes_semanales', models.TextField()),
                ('lunes', models.CharField(blank=True, max_length=255, null=True)),
                ('martes', models.TextField()),
                ('miercoles', models.CharField(blank=True, max_length=255, null=True)),
                ('jueves', models.CharField(blank=True, max_length=255, null=True)),
                ('viernes', models.TextField()),
                ('sabado', models.CharField(blank=True, max_length=255, null=True)),
                ('horario_lunes', models.CharField(blank=True, max_length=255, null=True)),
                ('horario_martes', models.TextField()),
                ('horario_miercoles', models.CharField(blank=True, max_length=255, null=True)),
                ('horario_jueves', models.CharField(blank=True, max_length=255, null=True)),
                ('horario_viernes', models.TextField()),
                ('horario_sabado', models.CharField(blank=True, max_length=255, null=True)),
                ('movimiento_agenda', models.TextField()),
                ('correo', models.TextField()),
                ('telefono', models.TextField()),
            ],
            options={
                'db_table': 'datos_medicos',
                'managed': False,
            },
        ),
    ]
